## 14. [Error Handling](https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html#)

   ```swift 
   enum AppError: Error {
     case invalidProductID
     case noData 
     case serverError
   }

   func fetchProductDetails(productID: Int) throws {
     if productID <= 0 {
       throw AppError.invalidProductID
     }
     print("Fetching details for product ID \(productID).")
   }

   do {
     try fetchProductDetails(productID: -1)
   } catch {
     print(error) // invalidProductID
   }

   do {
     try fetchProductDetails(productID: 101) // Fetching details for product ID 101.
   } catch {
     print(error)
   }
   ```
   
  ### Using `try!` and `try?`

  #### `try!`
  The `try!` keyword is used when you are certain that the function will not throw an error at runtime. If an error is thrown, the program will crash.

  ```swift
  do {
    try fetchProductDetails(productID: 101)
    print("Product details fetched successfully.")
  } catch {
    print(error)
  }

  // Using try!
  let productDetails = try! fetchProductDetails(productID: 101)
  print("Product details fetched successfully.")
  ```

  #### `try?`
  The `try?` keyword is used to handle errors by converting the result to an optional. If an error is thrown, the result will be `nil`.

  ```swift
  do {
    try fetchProductDetails(productID: 101)
    print("Product details fetched successfully.")
  } catch {
    print(error)
  }

  // Using try?
  if let productDetails = try? fetchProductDetails(productID: 101) {
    print("Product details fetched successfully.")
  } else {
    print("Failed to fetch product details.")
  }
  ```
